name: check styles, etc
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: install modules
        run: yarn install --no-lockfile
      - name: build project
        run: npm run build:prod
      - name: eslint typescript
        run: npm run lint:ts
        if: always()
      - name: stylelint css
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        id: lokitest
        run: npm run test:ui:ci
        if: always()

#      - name: Debug Job Failure
#        run: npm run test:ui:report
#        if: always() && (steps.lokitest.outcome == 'failure')
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v4
#        with:
#          name: loki test fail report
#          path: .loki/**/*
#        if: always() && (steps.lokitest.outcome == 'failure')



#      - name: install modules
#        run: npm install --legacy-peer-deps
#      - name: build project
#        run: npm run build:prod
#        if: always()
#      - name: eslint typescript
#        run: npm run lint:ts
#        if: always()
#      - name: stylelint css
#        run: npm run lint:scss
#      - name: unit testing
#        if: always()
#        run: npm run test:unit
#      - name: build storybook
#        run: npm run storybook:build
#        if: always()
#      - name: screenshot testing
#        run: npm run test:ui:ci
#        if: always()
